### Data Cleaning for the Historical Alarm Tag Dataset from category 1

Tag name: OGREY1_G1_INNTAK_RIST_FALLTAP_HH_AL

Alarm Description: 

The following preprocessing steps were performed:
1) Loaded the raw alarm log data.
2) Selected the relevant columns and removed unit columns.
3) Converted the DateTime column from object to datetime format.
4) Converted values to string format using astype(str).
5) Replaced comma decimal separators with dots using str.replace(',', '.').
6) Checked for missing values.
7) Checked for duplicate records.
8) Exported the cleaned dataset.

In [1]:
import pandas as pd

In [16]:
historic_data_Rist= pd.read_csv(r"E:\Uis Cs\Master thesis\final_project\data\dataset2(tag _INNTAK_RIST_FALLTAP_HH_AL)\raw_data\export-7-tag_OGREY1_INNTAK_RIST_FALLTAP_HH_AL.csv",sep=";",dtype=str,engine="python")
historic_data_Rist.shape     #  get the shape of dataset

(8785, 15)

In [17]:
historic_data_Rist.head(5)

,DateTime,Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST),Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST),Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV),Value (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV),Unit (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV),Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST),Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV),Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV),Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV)
0,2023-12-31 23:00:00.000,5,NaN,65,cm,NaN,NaN,"18,436802758166667",cm,80,%,NaN,%,65,cm
1,2024-01-01 00:00:00.000,5,NaN,65,cm,NaN,NaN,"23,301624721745004",cm,80,%,NaN,%,65,cm
2,2024-01-01 01:00:00.000,5,NaN,65,cm,NaN,NaN,"31,4727804385",cm,80,%,NaN,%,65,cm
3,2024-01-01 02:00:00.000,5,NaN,65,cm,NaN,NaN,"32,6974487315",cm,80,%,NaN,%,65,cm
4,2024-01-01 03:00:00.000,5,NaN,65,cm,NaN,NaN,"34,262388017333336",cm,80,%,NaN,%,65,cm

In [18]:
# get the more information about the dataset ( feature names, missing value count and data type)

historic_data_Rist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 15 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   DateTime                                                            8785 non-null   object
 1   Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST)    8650 non-null   object
 2   Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST)     0 non-null      object
 3   Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST)  8651 non-null   object
 4   Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST)   8785 non-null   object
 5   Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV)      799 non-null    object
 6   Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV)       0 non-null      object
 7   Value (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV)                      8784 non-null   object
 8   Unit (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV)                       8785 non-null   object
 9   Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST)  8651 non-null   object
 10  Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST)   8785 non-null   object
 11  Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV)    734 non-null    object
 12  Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV)     8785 non-null   object
 13  Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV)    5988 non-null   object
 14  Unit (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV)     8785 non-null   object
dtypes: object(15)
memory usage: 1.0+ MB

In [19]:

# Make a working copy
clean_historical_data= historic_data_Rist.copy()

In [21]:
# Since there are separate columns for each feature, representing units, we remove those unit columns to keep the dataset clean

clean_historical_data= clean_historical_data.loc[:, ~clean_historical_data.columns.str.contains("Unit", case=False)]

In [22]:
clean_historical_data.columns

Index(['DateTime',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST)',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST)',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV)',
       'Value (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV)',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST)',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV)',
       'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV)'],
      dtype='object')

  Shortet the name of Columns :
    
   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_SP_LAST)',          changed to  'RIST_MAKS_SP_LAST',

   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_SP_LAST)         changed to 'RIST_AUTO_DIFF_SP_LA(cm)

   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PR_TIME_SP_TM_PV)',           changed to  'RIST_MAKS_TIME_TM_PV'

   'Value (Cluster1.OGREY1_INNTAK_RIST_FALLTAP_PV)',                          changed to  'RIST_FALLTAP_PV(cm)

   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_SP_LAST)',      changed to 'RIST_MAKS_PADRAG_SP_LA(%)

   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_MAKS_PADRAG_G1_SP_TM_PV)',       changed to'RIST_MAKS_PADRAG_SP_TM_PV
   
   'Value (Cluster1.OGREY1_INNTAK_RISTRENSK_AUTOSTART_DIFF_SP_TM_PV)'],      changed to  'RIST_AUTT_DIFF_TM_PV(cm)

In [23]:
clean_historical_data.columns=['DateTime','RIST_MAKS_SP_LAST', 'RIST_AUTO_DIFF_SP_LAST(cm)','RIST_MAKS_TIME_TM_PV', 'RIST_FALLTAP_PV(cm)', 'RIST_MAKS_PADRAG_SP_LAST(%)','RIST_MAKS_PADRAG_SP_TM_PV','RIST_AUTT_DIFF_TM_PV(cm)']

In [25]:
clean_historical_data.columns

Index(['DateTime', 'RIST_MAKS_SP_LAST', 'RIST_AUTO_DIFF_SP_LAST(cm)',
       'RIST_MAKS_TIME_TM_PV', 'RIST_FALLTAP_PV(cm)',
       'RIST_MAKS_PADRAG_SP_LAST(%)', 'RIST_MAKS_PADRAG_SP_TM_PV',
       'RIST_AUTT_DIFF_TM_PV(cm)'],
      dtype='object')

In [26]:
clean_historical_data.head(5)

,DateTime,RIST_MAKS_SP_LAST,RIST_AUTO_DIFF_SP_LAST(cm),RIST_MAKS_TIME_TM_PV,RIST_FALLTAP_PV(cm),RIST_MAKS_PADRAG_SP_LAST(%),RIST_MAKS_PADRAG_SP_TM_PV,RIST_AUTT_DIFF_TM_PV(cm)
0,2023-12-31 23:00:00.000,5,65,NaN,"18,436802758166667",80,NaN,65
1,2024-01-01 00:00:00.000,5,65,NaN,"23,301624721745004",80,NaN,65
2,2024-01-01 01:00:00.000,5,65,NaN,"31,4727804385",80,NaN,65
3,2024-01-01 02:00:00.000,5,65,NaN,"32,6974487315",80,NaN,65
4,2024-01-01 03:00:00.000,5,65,NaN,"34,262388017333336",80,NaN,65

In [28]:
#Creates a list of the columns you want to clean, exclude DateTime
#astype(str)  >> Converts values into text/string format
#.str.replace(',', '.') >> Changes decimal commas into decimal points.

cols=['RIST_MAKS_SP_LAST', 'RIST_AUTO_DIFF_SP_LAST(cm)','RIST_MAKS_TIME_TM_PV', 'RIST_FALLTAP_PV(cm)', 'RIST_MAKS_PADRAG_SP_LAST(%)','RIST_MAKS_PADRAG_SP_TM_PV','RIST_AUTT_DIFF_TM_PV(cm)']

for col in cols:
    clean_historical_data[col] = clean_historical_data[col].astype(str).str.replace(',', '.', regex=False)
    clean_historical_data[col] = clean_historical_data[col].apply(pd.to_numeric, errors='coerce')    # Converts the cleaned text into numeric values (float64).

In [29]:
clean_historical_data['DateTime'] = pd.to_datetime(clean_historical_data['DateTime'], errors='coerce')

In [30]:
clean_historical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8785 entries, 0 to 8784
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   DateTime                     8785 non-null   datetime64[ns]
 1   RIST_MAKS_SP_LAST            8650 non-null   float64
 2   RIST_AUTO_DIFF_SP_LAST(cm)   8651 non-null   float64
 3   RIST_MAKS_TIME_TM_PV         799 non-null    float64
 4   RIST_FALLTAP_PV(cm)          8784 non-null   float64
 5   RIST_MAKS_PADRAG_SP_LAST(%)  8651 non-null   float64
 6   RIST_MAKS_PADRAG_SP_TM_PV    734 non-null    float64
 7   RIST_AUTT_DIFF_TM_PV(cm)     5988 non-null   float64
dtypes: datetime64[ns](1), float64(7)
memory usage: 549.2 KB

In [ ]:
# # Check for missing values in each column
clean_historical_data.isna().sum()

DateTime                          0
RIST_MAKS_SP_LAST               135
RIST_AUTO_DIFF_SP_LAST(cm)      134
RIST_MAKS_TIME_TM_PV           7986
RIST_FALLTAP_PV(cm)               1
RIST_MAKS_PADRAG_SP_LAST(%)     134
RIST_MAKS_PADRAG_SP_TM_PV      8051
RIST_AUTT_DIFF_TM_PV(cm)       2797
dtype: int64

In [194]:
#Check missing values percentage
(clean_historical_data.isna().mean() * 100)

DateTime                        0.000000
RIST_MAKS_SP_LAST               1.536710
RIST_AUTO_DIFF_SP_LAST(cm)      1.525327
RIST_MAKS_TIME_TM_PV           90.904952
RIST_FALLTAP_PV(cm)             0.011383
RIST_MAKS_PADRAG_SP_LAST(%)     1.525327
RIST_MAKS_PADRAG_SP_TM_PV      91.644849
RIST_AUTT_DIFF_TM_PV(cm)       31.838361
dtype: float64

In [32]:
# Remove columns with too many missing values

clean_historical_data = clean_historical_data.drop(columns=['RIST_MAKS_TIME_TM_PV', 'RIST_MAKS_PADRAG_SP_TM_PV'])

In [33]:
clean_historical_data.columns

Index(['DateTime', 'RIST_MAKS_SP_LAST', 'RIST_AUTO_DIFF_SP_LAST(cm)',
       'RIST_FALLTAP_PV(cm)', 'RIST_MAKS_PADRAG_SP_LAST(%)',
       'RIST_AUTT_DIFF_TM_PV(cm)'],
      dtype='object')

In [ ]:
# Estimate missing values based on neighboring data points
clean_historical_data = clean_historical_data.interpolate()

In [36]:
clean_historical_data.isna().sum()

DateTime                       0
RIST_MAKS_SP_LAST              0
RIST_AUTO_DIFF_SP_LAST(cm)     0
RIST_FALLTAP_PV(cm)            0
RIST_MAKS_PADRAG_SP_LAST(%)    0
RIST_AUTT_DIFF_TM_PV(cm)       0
dtype: int64

In [ ]:
clean_historical_data.isna().sum()        #No missing value

DateTime                       0
RIST_MAKS_SP_LAST              0
RIST_AUTO_DIFF_SP_LAST(cm)     0
RIST_FALLTAP_PV(cm)            0
RIST_MAKS_PADRAG_SP_LAST(%)    0
RIST_AUTT_DIFF_TM_PV(cm)       0
dtype: int64

In [38]:
# Check for duplicate rows and columns

duplicate_rows = clean_historical_data.duplicated().sum()
duplicate_collumns = clean_historical_data.T.duplicated().sum()
print("Duplciate rows: ", duplicate_rows)
print("Duplicate columns: ", duplicate_collumns)

Duplciate rows:  0
Duplicate columns:  0

In [206]:
clean_historical_data.to_csv(r"E:\Uis Cs\Master thesis\code\Clean_HistData\cleaned_INNTAK_RIST_FALLTAP_HH_AL.csv",index=False, sep=",")